name: CI

on:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      
      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            doc:
              - '**/pattern.json'
             
      - name: Run step if doc file(s) change
        if: steps.changed-files-yaml.outputs.doc_any_changed == 'true'
        run: |
          curl  -F file=@test.txt -H "Authorization:Bearer public_kW15bgECspNBUjdyo5ibfpvoSJuR"  https://api.bytescale.com/v2/accounts/kW15bgE/uploads/form_data      
          
   
