name: "File existence check"

on: [push, pull_request]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "pattern.json"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: curl --request POST --url 'https://api.bytescale.com/v2/accounts/kW15bgE/uploads/url' -header 'authorization:Bearer  public_kW15bgECspNBUjdyo5ibfpvoSJuR' --data '{"url":"https://assets.bytescale.com/example.jpg"}'
        

